export const PATH = {
  GLOBAL: '/*',
  HOME: '/',
  HOMEPAGE: '/homepage',
  LOGIN: '/',
  SIDEBAR: '/sidebar',
  ASSIGN: '/assign',
  JOBS: '/jobs',
  INTERVIEWEEDETAILS: '/interviewee-details',
  DASHBOARD: '/dashboard',
  SELECTROLE: '/select-role',
  REGISTER_COMPANY: '/register-company',
  REGISTER: '/register',
  UNAUTHORIZED: '/unauthorized',
  MISSING: '/missing',
};
